(function(){
'use strict';
const C=()=>window.PrismaCore,S=()=>C().S,DB=()=>window.PrismaDB;
const esc=v=>C().esc(v),fmt=n=>C().fmt(n);

async function renderOperations(){
  const host=document.getElementById('page-operations');if(!host)return;
  host.innerHTML='<div class="hero"><h2>ACESSOS <b>OPERAÇÕES</b></h2><p>Abra ponto, máquina ou chamado no sistema certo sem decorar URL. Chamado só abre direto quando o ID interno estiver mapeado.</p></div>'+
  '<div class="card"><div class="card-body"><div class="search-row"><input id="opsSearch" placeholder="Ponto, máquina ou chamado…"><button id="opsRun" class="primary">Pesquisar</button></div></div></div><div id="opsOut"></div>';
  const run=async()=>{const q=document.getElementById('opsSearch').value.trim(),out=document.getElementById('opsOut');if(!q){out.innerHTML='<div class="card empty">Digite algo.</div>';return}const rows=await C().search(q,40,'all'),tm=await DB().all('ticketMap');const keep=rows.filter(r=>['point','machine','ticket'].includes(r.type));out.innerHTML='<div class="card"><div class="card-body">'+(keep.length?keep.map(r=>{if(r.type==='point'){const p=r.entity;return '<div class="source-row"><div><b>'+esc((p.code?p.code+' • ':'')+p.name)+'</b><small>Ponto • '+esc(p.address||'')+'</small></div><a class="btn primary" target="_blank" rel="noopener" href="'+esc(C().operationsPointUrl(p))+'">Abrir ↗</a></div>'}if(r.type==='machine'){const m=r.entity;return '<div class="source-row"><div><b>'+esc('['+m.id+'] '+m.name)+'</b><small>Máquina • '+esc([m.pointCode,m.square].filter(Boolean).join(' • '))+'</small></div><a class="btn primary" target="_blank" rel="noopener" href="'+esc(C().operationsMachineUrl(m))+'">Abrir ↗</a></div>'}const id=r.key,map=tm.find(x=>x.ticket===id),url=map?'https://operacoes.eletromidia.com.br/tickets/'+encodeURIComponent(map.internalId)+'/edit':'';return '<div class="source-row"><div><b>Chamado '+esc(id)+'</b><small>'+(map?'ID interno '+esc(map.internalId):'ID interno não mapeado')+'</small></div>'+(url?'<a class="btn primary" target="_blank" rel="noopener" href="'+esc(url)+'">Abrir ↗</a>':'<button data-copy-ticket="'+esc(id)+'">Copiar ELT</button>')+'</div>'}).join(''):'<div class="empty">Nenhum acesso encontrado.</div>')+'</div></div>';out.querySelectorAll('[data-copy-ticket]').forEach(b=>b.onclick=()=>navigator.clipboard?.writeText(b.dataset.copyTicket).then(()=>C().toast('Chamado copiado')))};
  document.getElementById('opsRun').onclick=run;document.getElementById('opsSearch').onkeydown=e=>{if(e.key==='Enter')run()};
}
async function renderLocal(){
  const host=document.getElementById('page-local');if(!host)return;const pass=await DB().all('passwords'),notes=await DB().all('notes');
  host.innerHTML='<div class="hero"><h2>DADOS <b>LOCAIS</b></h2><p>Senhas e notas operacionais ficam apenas no IndexedDB da V12. A fonte original não é alterada.</p></div>'+
  '<div class="grid2"><div class="card"><div class="card-head"><h3>Senhas locais</h3><small>'+fmt(pass.length)+'</small></div><div class="card-body"><div class="search-row"><input id="localPassSearch" placeholder="ID da máquina…"><button id="newLocalPass">Adicionar</button></div><div id="localPassList"></div></div></div>'+
  '<div class="card"><div class="card-head"><h3>Notas locais</h3><small>'+fmt(notes.length)+'</small></div><div class="card-body"><div class="search-row"><input id="localNoteSearch" placeholder="ponto, máquina, mensagem…"></div><div id="localNoteList"></div></div></div></div>';
  const draw=()=>{const pq=C().norm(document.getElementById('localPassSearch').value),nq=C().norm(document.getElementById('localNoteSearch').value);document.getElementById('localPassList').innerHTML=pass.filter(x=>!pq||C().norm(x.id).includes(pq)).slice(0,300).map(x=>'<div class="source-row"><div><b>Máquina '+esc(x.id)+'</b><small>••••••••</small></div><div class="actions"><button data-show-pass="'+esc(x.id)+'">Mostrar</button><button class="danger" data-del-pass="'+esc(x.id)+'">Excluir</button></div></div>').join('')||'<div class="empty">Nenhuma senha.</div>';document.getElementById('localNoteList').innerHTML=notes.filter(x=>!nq||C().norm(x.id+' '+x.value).includes(nq)).slice(0,300).map(x=>'<div class="source-row"><div><b>'+esc(x.id)+'</b><small>'+esc(String(x.value||'').slice(0,180))+'</small></div><button class="danger" data-del-note="'+esc(x.id)+'">Excluir</button></div>').join('')||'<div class="empty">Nenhuma nota.</div>';bind();};
  const bind=()=>{host.querySelectorAll('[data-show-pass]').forEach(b=>b.onclick=async()=>{const x=await DB().get('passwords',b.dataset.showPass);if(x)prompt('Senha da máquina '+x.id+':',x.value)});host.querySelectorAll('[data-del-pass]').forEach(b=>b.onclick=async()=>{if(confirm('Excluir esta senha local?')){await DB().delete('passwords',b.dataset.delPass);renderLocal()}});host.querySelectorAll('[data-del-note]').forEach(b=>b.onclick=async()=>{if(confirm('Excluir esta nota local?')){await DB().delete('notes',b.dataset.delNote);renderLocal()}})};
  document.getElementById('localPassSearch').oninput=draw;document.getElementById('localNoteSearch').oninput=draw;document.getElementById('newLocalPass').onclick=()=>{PrismaApp.showModal('<h3 style="margin-top:0">Senha local</h3><label>ID da máquina<input id="lpId"></label><label style="display:block;margin-top:8px">Senha<input id="lpValue"></label><div class="actions"><button data-modal-close>Cancelar</button><button id="lpSave" class="primary">Salvar</button></div>');document.querySelector('[data-modal-close]').onclick=PrismaApp.closeModal;document.getElementById('lpSave').onclick=async()=>{const id=document.getElementById('lpId').value.trim(),value=document.getElementById('lpValue').value;if(!id)return;await DB().put('passwords',{id,value,updatedAt:new Date().toISOString()});PrismaApp.closeModal();renderLocal()}};draw();
}
window.PrismaAccess={renderOperations,renderLocal};
})();